# Generated by Django 5.2.9 on 2025-12-03 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
